<a href="https://colab.research.google.com/github/Dfiora/Dfiora/blob/main/P3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_excel('base p3.xlsx') # Substitua 'seu_arquivo.xlsx' pelo nome do seu arquivo

In [7]:
%whos #mostra todas as variáveis ativas

Variable          Type         Data/Info
----------------------------------------
df                DataFrame                 nome_pesquis<...>n[283 rows x 787 columns]
num_observacoes   int          283
num_variaveis     int          787
pd                module       <module 'pandas' from '/u<...>ages/pandas/__init__.py'>

In [8]:
#retorna lista com todos os nomes de variáveis criadas no notebook
list(globals().keys())

['__name__',
 '__doc__',
 '__package__',
 '__loader__',
 '__spec__',
 '__builtin__',
 '__builtins__',
 '_ih',
 '_oh',
 '_dh',
 'In',
 'Out',
 'get_ipython',
 'exit',
 'quit',
 '_',
 '__',
 '___',
 '_i',
 '_ii',
 '_iii',
 '_i1',
 'pd',
 'df',
 '_i2',
 '__js_239',
 '_i3',
 '_i4',
 'num_observacoes',
 '_i5',
 'num_variaveis',
 '_i6',
 '_i7',
 '_i8']

In [14]:
type(base p3.xlsx)

pandas.core.frame.DataFrame

In [15]:
import pandas as pd

# Junta as 5 primeiras e as 5 últimas linhas
df_head_tail = pd.concat([df.head(5), df.tail(5)])

# Exibe o resultado
display(df_head_tail)

,nome_pesquisa,id_resposta,data_hora_criacao,data_hora_envio,status,percentual_respondido,id_organizacao,razao_social,nome_fantasia,cnpj_organizacao,...,16.3.3. percentual_LAJIR_2022,16.3.4. percentual_LAJIR_2023,16.3.5. percentual_LAJIR_2024,16.4.1. tabela_custos_servicos_preco_armazenagem,16.4.2. tabela_custos_servicos_preco_movimentacao,16.4.3. tabela_custos_servicos_servicos_complementares,16.4.4. tabela_custos_servicos_THC,16.4.5. tabela_custos_servicos_THC2,16.4.6. tabela_custos_servicos_outros,16.5. informacao_adicional
0,Diagnóstico de Portos,1739.0,2025-01-30 11:53:02,NaT,Em andamento,0.267857,3422,NAVEGANTES LOGISTICA PORTUARIA S.A.,NAVEGANTES LOGISTICA PORTUARIA S.A.,10.000.000/0000-69,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Diagnóstico de Portos,1740.0,2025-01-30 12:18:45,2025-04-28 13:15:00,Concluído,0.946429,3423,TEG - TERMINAL EXPORTADOR DO GUARUJA LTDA.,TEG - TERMINAL EXPORTADOR DO GUARUJA LTDA.,10.000.000/0001-30,...,0.0,0.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Diagnóstico de Portos,1741.0,2025-01-30 12:53:02,2025-02-14 16:17:00,Concluído,0.910714,3424,TERMINAL PORTUÁRIO COTEGIPE,TERMINAL PORTUÁRIO COTEGIPE,10.000.000/0002-03,...,74.0,72.5,66.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Diagnóstico de Portos,1742.0,2025-01-30 14:03:21,2025-03-23 17:33:00,Concluído,0.857143,3425,TUP TROCADEIRO,TUP TROCADEIRO,10.000.000/0003-26,...,0.0,0.0,2074569.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Diagnóstico de Portos,1743.0,2025-01-30 14:46:15,2025-02-28 20:48:00,Concluído,0.839286,3426,SUPER TERMINAIS COMERCIO E INDUSTRIA LTDA.,SUPER TERMINAIS COMERCIO E INDUSTRIA LTDA.,10.000.000/0001-73,...,67.0,51.0,53.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278,Diagnóstico de Portos,NaN,NaT,NaT,Não iniciado,0.000000,3542,PORTO DE ITAQUI - EMAP,PORTO DE ITAQUI - EMAP,10.000.000/0010-00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,Diagnóstico de Portos,NaN,NaT,NaT,Não iniciado,0.000000,3548,TERMINAL AQUAVIÁRIO DE SÃO FRANCISCO DO SUL,TERMINAL AQUAVIÁRIO DE SÃO FRANCISCO DO SUL,10.000.000/0003-98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
280,Diagnóstico de Portos,NaN,NaT,NaT,Não iniciado,0.000000,3551,Terminal de Regaseificação do Açu,Terminal de Regaseificação do Açu,10.000.000/0004-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281,Diagnóstico de Portos,NaN,NaT,NaT,Não iniciado,0.000000,3553,Administradora de Bens de Infraestrutura Ltda....,Administradora de Bens de Infraestrutura Ltda....,10.000.000/0004-03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,Diagnóstico de Portos,NaN,NaT,NaT,Não iniciado,0.000000,3554,TUP ALISEO,TUP ALISEO,10.000.000/0004-04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df = df.dropna(how="all").reset_index(drop=True)
%whos

Variable          Type         Data/Info
----------------------------------------
df                DataFrame                 nome_pesquis<...>n[283 rows x 787 columns]
df_head_tail      DataFrame                 nome_pesquis<...>\n[10 rows x 787 columns]
num_observacoes   int          283
num_variaveis     int          787
pd                module       <module 'pandas' from '/u<...>ages/pandas/__init__.py'>

In [18]:
# Excluir somente as linhas totalmente vazias
df = df.dropna(how="all").reset_index(drop=True)

# Conferir resultado
display(df.head())
display(df.tail())

,nome_pesquisa,id_resposta,data_hora_criacao,data_hora_envio,status,percentual_respondido,id_organizacao,razao_social,nome_fantasia,cnpj_organizacao,...,16.3.3. percentual_LAJIR_2022,16.3.4. percentual_LAJIR_2023,16.3.5. percentual_LAJIR_2024,16.4.1. tabela_custos_servicos_preco_armazenagem,16.4.2. tabela_custos_servicos_preco_movimentacao,16.4.3. tabela_custos_servicos_servicos_complementares,16.4.4. tabela_custos_servicos_THC,16.4.5. tabela_custos_servicos_THC2,16.4.6. tabela_custos_servicos_outros,16.5. informacao_adicional
0,Diagnóstico de Portos,1739.0,2025-01-30 11:53:02,NaT,Em andamento,0.267857,3422,NAVEGANTES LOGISTICA PORTUARIA S.A.,NAVEGANTES LOGISTICA PORTUARIA S.A.,10.000.000/0000-69,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Diagnóstico de Portos,1740.0,2025-01-30 12:18:45,2025-04-28 13:15:00,Concluído,0.946429,3423,TEG - TERMINAL EXPORTADOR DO GUARUJA LTDA.,TEG - TERMINAL EXPORTADOR DO GUARUJA LTDA.,10.000.000/0001-30,...,0.0,0.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Diagnóstico de Portos,1741.0,2025-01-30 12:53:02,2025-02-14 16:17:00,Concluído,0.910714,3424,TERMINAL PORTUÁRIO COTEGIPE,TERMINAL PORTUÁRIO COTEGIPE,10.000.000/0002-03,...,74.0,72.5,66.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Diagnóstico de Portos,1742.0,2025-01-30 14:03:21,2025-03-23 17:33:00,Concluído,0.857143,3425,TUP TROCADEIRO,TUP TROCADEIRO,10.000.000/0003-26,...,0.0,0.0,2074569.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Diagnóstico de Portos,1743.0,2025-01-30 14:46:15,2025-02-28 20:48:00,Concluído,0.839286,3426,SUPER TERMINAIS COMERCIO E INDUSTRIA LTDA.,SUPER TERMINAIS COMERCIO E INDUSTRIA LTDA.,10.000.000/0001-73,...,67.0,51.0,53.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,nome_pesquisa,id_resposta,data_hora_criacao,data_hora_envio,status,percentual_respondido,id_organizacao,razao_social,nome_fantasia,cnpj_organizacao,...,16.3.3. percentual_LAJIR_2022,16.3.4. percentual_LAJIR_2023,16.3.5. percentual_LAJIR_2024,16.4.1. tabela_custos_servicos_preco_armazenagem,16.4.2. tabela_custos_servicos_preco_movimentacao,16.4.3. tabela_custos_servicos_servicos_complementares,16.4.4. tabela_custos_servicos_THC,16.4.5. tabela_custos_servicos_THC2,16.4.6. tabela_custos_servicos_outros,16.5. informacao_adicional
278,Diagnóstico de Portos,NaN,NaT,NaT,Não iniciado,0.0,3542,PORTO DE ITAQUI - EMAP,PORTO DE ITAQUI - EMAP,10.000.000/0010-00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,Diagnóstico de Portos,NaN,NaT,NaT,Não iniciado,0.0,3548,TERMINAL AQUAVIÁRIO DE SÃO FRANCISCO DO SUL,TERMINAL AQUAVIÁRIO DE SÃO FRANCISCO DO SUL,10.000.000/0003-98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
280,Diagnóstico de Portos,NaN,NaT,NaT,Não iniciado,0.0,3551,Terminal de Regaseificação do Açu,Terminal de Regaseificação do Açu,10.000.000/0004-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281,Diagnóstico de Portos,NaN,NaT,NaT,Não iniciado,0.0,3553,Administradora de Bens de Infraestrutura Ltda....,Administradora de Bens de Infraestrutura Ltda....,10.000.000/0004-03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,Diagnóstico de Portos,NaN,NaT,NaT,Não iniciado,0.0,3554,TUP ALISEO,TUP ALISEO,10.000.000/0004-04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# Número de linhas antes da limpeza
linhas_antes = len(df)

# Remove somente linhas totalmente vazias
df = df.dropna(how="all").reset_index(drop=True)

# Número de linhas depois da limpeza
linhas_depois = len(df)

# Quantas foram removidas
removidas = linhas_antes - linhas_depois

print(f"Linhas antes: {linhas_antes}")
print(f"Linhas depois: {linhas_depois}")
print(f"Total removidas: {removidas}")

Linhas antes: 283
Linhas depois: 283
Total removidas: 0

In [20]:
import numpy as np

# Substitui células vazias ou só com espaços por NaN
df = df.replace(r'^\s*$', np.nan, regex=True)

# Agora remove linhas totalmente vazias
df = df.dropna(how="all").reset_index(drop=True)

display(df.head())
display(df.tail())

,nome_pesquisa,id_resposta,data_hora_criacao,data_hora_envio,status,percentual_respondido,id_organizacao,razao_social,nome_fantasia,cnpj_organizacao,...,16.3.3. percentual_LAJIR_2022,16.3.4. percentual_LAJIR_2023,16.3.5. percentual_LAJIR_2024,16.4.1. tabela_custos_servicos_preco_armazenagem,16.4.2. tabela_custos_servicos_preco_movimentacao,16.4.3. tabela_custos_servicos_servicos_complementares,16.4.4. tabela_custos_servicos_THC,16.4.5. tabela_custos_servicos_THC2,16.4.6. tabela_custos_servicos_outros,16.5. informacao_adicional
0,Diagnóstico de Portos,1739.0,2025-01-30 11:53:02,NaT,Em andamento,0.267857,3422,NAVEGANTES LOGISTICA PORTUARIA S.A.,NAVEGANTES LOGISTICA PORTUARIA S.A.,10.000.000/0000-69,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Diagnóstico de Portos,1740.0,2025-01-30 12:18:45,2025-04-28 13:15:00,Concluído,0.946429,3423,TEG - TERMINAL EXPORTADOR DO GUARUJA LTDA.,TEG - TERMINAL EXPORTADOR DO GUARUJA LTDA.,10.000.000/0001-30,...,0.0,0.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Diagnóstico de Portos,1741.0,2025-01-30 12:53:02,2025-02-14 16:17:00,Concluído,0.910714,3424,TERMINAL PORTUÁRIO COTEGIPE,TERMINAL PORTUÁRIO COTEGIPE,10.000.000/0002-03,...,74.0,72.5,66.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Diagnóstico de Portos,1742.0,2025-01-30 14:03:21,2025-03-23 17:33:00,Concluído,0.857143,3425,TUP TROCADEIRO,TUP TROCADEIRO,10.000.000/0003-26,...,0.0,0.0,2074569.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Diagnóstico de Portos,1743.0,2025-01-30 14:46:15,2025-02-28 20:48:00,Concluído,0.839286,3426,SUPER TERMINAIS COMERCIO E INDUSTRIA LTDA.,SUPER TERMINAIS COMERCIO E INDUSTRIA LTDA.,10.000.000/0001-73,...,67.0,51.0,53.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,nome_pesquisa,id_resposta,data_hora_criacao,data_hora_envio,status,percentual_respondido,id_organizacao,razao_social,nome_fantasia,cnpj_organizacao,...,16.3.3. percentual_LAJIR_2022,16.3.4. percentual_LAJIR_2023,16.3.5. percentual_LAJIR_2024,16.4.1. tabela_custos_servicos_preco_armazenagem,16.4.2. tabela_custos_servicos_preco_movimentacao,16.4.3. tabela_custos_servicos_servicos_complementares,16.4.4. tabela_custos_servicos_THC,16.4.5. tabela_custos_servicos_THC2,16.4.6. tabela_custos_servicos_outros,16.5. informacao_adicional
278,Diagnóstico de Portos,NaN,NaT,NaT,Não iniciado,0.0,3542,PORTO DE ITAQUI - EMAP,PORTO DE ITAQUI - EMAP,10.000.000/0010-00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,Diagnóstico de Portos,NaN,NaT,NaT,Não iniciado,0.0,3548,TERMINAL AQUAVIÁRIO DE SÃO FRANCISCO DO SUL,TERMINAL AQUAVIÁRIO DE SÃO FRANCISCO DO SUL,10.000.000/0003-98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
280,Diagnóstico de Portos,NaN,NaT,NaT,Não iniciado,0.0,3551,Terminal de Regaseificação do Açu,Terminal de Regaseificação do Açu,10.000.000/0004-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281,Diagnóstico de Portos,NaN,NaT,NaT,Não iniciado,0.0,3553,Administradora de Bens de Infraestrutura Ltda....,Administradora de Bens de Infraestrutura Ltda....,10.000.000/0004-03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,Diagnóstico de Portos,NaN,NaT,NaT,Não iniciado,0.0,3554,TUP ALISEO,TUP ALISEO,10.000.000/0004-04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
import numpy as np

# Cria uma cópia temporária para checar
df_temp = df.replace(r'^\s*$', np.nan, regex=True)

# Localiza linhas totalmente vazias (todas as colunas == NaN)
linhas_ocultas = df_temp[df_temp.isna().all(axis=1)]

# Conta quantas são
qtd_ocultas = len(linhas_ocultas)

print(f"Linhas totalmente vazias (incluindo as 'ocultas'): {qtd_ocultas}")

# Se quiser ver os índices originais dessas linhas
print("Índices das linhas vazias:", linhas_ocultas.index.tolist())

Linhas totalmente vazias (incluindo as 'ocultas'): 0
Índices das linhas vazias: []

In [22]:
import numpy as np

# 1. Substituir células só com espaços por NaN
df = df.replace(r'^\s*$', np.nan, regex=True)

# 2. Contar quantas linhas ficaram totalmente vazias
linhas_ocultas = df[df.isna().all(axis=1)]
qtd_ocultas = len(linhas_ocultas)

print(f"Linhas totalmente vazias (incluindo ocultas): {qtd_ocultas}")
print("Índices removidos:", linhas_ocultas.index.tolist())

# 3. Excluir essas linhas e resetar índice
df = df.dropna(how="all").reset_index(drop=True)

print(f"Novo tamanho da base: {len(df)} linhas")

Linhas totalmente vazias (incluindo ocultas): 0
Índices removidos: []
Novo tamanho da base: 283 linhas